# Generated by Django 5.0.6 on 2024-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_dislike_count_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='email'),
        ),
    ]
